//int const BufferIOFileClass::Is_Open(void)
//BufferIOFileClass::BufferIOFileClass(char *)
//BufferIOFileClass::BufferIOFileClass(void)
//int BufferIOFileClass::Cache(long, void *)
//void BufferIOFileClass::Close(void)
//int BufferIOFileClass::Commit(void)
//void BufferIOFileClass::Free(void)
//int BufferIOFileClass::Is_Available(int)
//int BufferIOFileClass::Open(char *, int)
//int BufferIOFileClass::Open(int)
//long BufferIOFileClass::Read(void *, long)
//long BufferIOFileClass::Seek(long, int)
//char * BufferIOFileClass::Set_Name(char *)
//long BufferIOFileClass::Size(void)
//long BufferIOFileClass::Write(void *, long)
//BufferIOFileClass::~BufferIOFileClass(void)